# Site settings
name: BLOG
email: 2510764133@qq.com
author: huangwei
url: https://mayunmeiyouming.github.io/blog/
resume_site: https://mayunmeiyouming.github.io/blog/
github: https://github.com/mayunmeiyouming
baseurl: "/"
description: 学而不思则罔，思而不学则殆。
meta_description: linux;C;Java;
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: mayunmeiyouming

# Build settings
markdown: kramdown

baidu_analysis: 732119f324b13d7ba962f0d22dd41759

